import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { rollup } from 'rollup';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import { ivi } from '@ivi/rollup-plugin';

const entry = new URL('../src/legend.js', import.meta.url);
const target = new URL('../src/legend-ivi.js', import.meta.url);
const bundle = await rollup({
	input: fileURLToPath(entry),
	plugins: [ivi(), nodeResolve({ browser: true })],
	onwarn(warning, warn) {
		if (warning.code === 'UNRESOLVED_IMPORT')
			throw new Error(warning.message);
		warn(warning);
	},
});

try {
	const result = await bundle.generate({
		format: 'iife',
		name: '__legend',
		exports: 'named',
		esModule: false,
		inlineDynamicImports: true,
	});
	const chunk = result.output[0];
	if (result.output.length !== 1 || chunk.type !== 'chunk' || chunk.imports.length || chunk.dynamicImports.length)
		throw new Error('Legend must compile to one self-contained JavaScript chunk.');
	if (chunk.exports.length !== 1 || chunk.exports[0] !== 'createLegend')
		throw new Error('Legend must export only createLegend.');

	const sourceHash = createHash('sha256').update(await readFile(entry)).digest('hex');

	// Delay ivi's DOM prototype and template initialization until chart construction.
	const code = '// Generated by scripts/build-legend.mjs. Do not edit.\n' +
		`// Source hash: ${sourceHash}\n` +
		'// @ts-nocheck\n' +
		'let create;\n' +
		'export function createLegend(self, parent, opts) {\n' +
		'\tif (create === undefined) {\n' +
		chunk.code.split('\n').map(line => line.trimEnd()).map(line => line ? '\t\t' + line : '').join('\n') + '\n' +
		'\t\tcreate = __legend.createLegend;\n' +
		'\t}\n\treturn create(self, parent, opts);\n}\n';
	await writeFile(target, code);
	console.log(`build:legend: src/legend-ivi.js (${Buffer.byteLength(code)} bytes)`);
}
finally {
	await bundle.close();
}
